:toc: macro
:toclevels: 3

# Gradient
This repository serves as a public issue tracker and documentation for Gradient, full TensorFlow binding for .NET

You can find samples at https://github.com/losttech/Gradient-Samples

toc::[]

# Getting started
## Installation
Tech Preview is currently limited to Windows x64 machines, and full .NET Framework 4.7.1+ targets.

### Install Python + Tensorflow
Before installing Gradient, you should ensure, that you have TensorFlow installed and working:

. Install Python 3.6 64-bit. If you have Visual Studio 2017+, it is possible to install it as a component. Otherwise, get one from https://www.python.org/downloads/
. Install TensorFlow 1.10 using pip:
.. Find `python.exe` in the installation directory (VS installs it C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe)
.. Open command line to the directory, containing `python.exe`
.. Execute `.\python.exe -m pip install tensorflow==1.10.\*` or `.\python.exe -m pip install tensorflow-gpu==1.10.*` if you want GPU acceleration via CUDA
.. Launch `python.exe`, and try running `import tensorflow`. It should succeed.

### Add Nuget package to your project

Gradient packages are published on https://www.nuget.org/packages/Gradient/[Nuget], but will not be "listed" until about Tech Preview 5, which means you won't be able to find it in the Nuget Package Manager. Nuget page lists the commands, necessary to install the package into your project. As of preview1 and the new .csproj format, the command is

[source,powershell]
----
dotnet add package Gradient --version 0.1.10-tech-preview1 
----

If using the new package management features of `.csproj`, this could also be achieved by adding the following line to it:

[source,xml]
----
<PackageReference Include="Gradient" Version="0.1.10-tech-preview1"  />
----

See the example project file https://github.com/losttech/Gradient-Samples/blob/master/BasicMath/BasicMath.csproj[here].

## First steps

### Namespaces
In most cases, you will need to add `using tensorflow;` at the beginning of your file. In many cases you will also need `using Gradient;` and `using numpy;`.

[source,csharp]

[source,csharp]
----
using numpy;
using tensorflow;
using Gradient;
----

### Old style TF
Prior to the recent changes, the main way to use TensorFlow was to contstruct a computation graph, and then run it in a session. Most of the existing examples will use this mode.

#### Constructing compute graph
Graph creation methods are located in the `tf` class from `tensorflow` namespace. For example:

[source,csharp]
----
var a = new dynamic[] { tf.constant(5.0, name: "a") };
var b = new dynamic[] { tf.constant(10.0, name: "b") };

var sum = new dynamic[] { tf.add(a, b, name: "sum") };
var div = new dynamic[] { tf.div(a, b, name: "div") };
----

In this case we wrap the resulting `Tensor` objects into an array, as many construction functions in Gradient like `tf.add` expect arrays (or rather `IEnumerable`), not individual `Tensor` values. (that might change in the future)

#### Running computation
Next, you need to create a `Session` to run your graph one or multiple times. Sessions allocate CPU, GPU and memory resources, and hold the states of variables.

NOTE: In GPU mode, TensorFlow will attempt to allocate all the GPU memory to itself at that stage,
so ensure you don't have any other programs extensively using it, or https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory[turn down TensorFlow memory allocation] (has not been tested in Gradient Tech Preview)

Since TensorFlow sessions hold unmanaged resources, they have to be used similar to (but not idential to) `IDisposable`:

[source,csharp]
----
new Session().UseSelf(session => {
    ...do something with the session...
});
----

Now that you have a `Session` to work with, you can actually compute the values in the graph:

[source,csharp]
----
new Session().UseSelf(session => {
    Console.WriteLine($"a = {session.run(a)}");
    Console.WriteLine($"b = {session.run(b)}");
    Console.WriteLine($"a + b = {session.run(sum)}");
    Console.WriteLine($"a / b = {session.run(div)}");
});
----

Note, that `Session.run` also takes a sequence of `Tensor`-like objects.

The full code for this example is available at our https://github.com/losttech/Gradient-Samples/tree/master/BasicMath[samples repository]

# Porting Python code
TBD
